---
title: "rf_150_samples"
author: "Mihkail Cornell"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
set.seed(231)
doParallel::registerDoParallel()

landmarks150_rf_spec <- 
  rand_forest(
      mtry  = tune(),
      trees = 1000,
      min_n = tune()
    ) %>% 
  set_mode("classification") %>%
  set_engine("ranger")



```



```{r}
landmarks150_wf <-
  workflow() %>%
  add_recipe(landmarks150_rec) %>%
  add_model(landmarks150_rf_spec)
```



```{r}
set.seed(234)
landmarks150_folds <- vfold_cv(landmarks150_train)


doParallel::registerDoParallel()
set.seed(345)

rf_results <- 
  tune_grid(
  landmarks150_wf,
  resamples = landmarks150_folds,
  grid = 10
)

best_accuracy <- rf_results %>% select_best("accuracy")
```

```{r}
final_rf <- landmarks150_wf %>% 
  finalize_workflow(select_best(rf_results, "accuracy"))


landmarks150_fit <- last_fit(final_rf, landmarks150_split)


rf_final_ <- 
  finalize_model(
    landmarks150_rf_spec,
    best_accuracy
  )
```

```{r}
rf_final_wf <- 
  workflow() %>%
  add_recipe(landmarks150_rec) %>%
  add_model(rf_final_)


rf_final_results <-
  rf_final_wf %>%
  last_fit(landmarks150_split)

collect_metrics(rf_final_results)

rf_final_results %>% collect_predictions()
```

```{r}
rf_final_results$.workflow[[1]] 

rf_final_results$.predictions
  
rf_final_results$.metrics[[1]]



```

```{r}
write.csv(data.frame(rf_final_results$.predictions), "rf150_pred.csv", row.names = FALSE)
```

