---
title: "svm_250_samples"
author: "Mihkail Cornell"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(parallel)

doParallel::registerDoParallel()
set.seed(342)

svm250_linear_tune <-
  svm_linear(
    cost = tune()
  ) %>%
  set_mode("classification") %>%
  set_engine("kernlab")

svm250_grid <- 
  expand.grid(cost = c(0.25, 0.5, 0.75, 1, 1.25, 1.5))


svm250_linear_wf <-
  workflow() %>%
  add_recipe(landmarks250_rec) %>%
  add_model(svm250_linear_tune)

# Tuning is faster in parallel
all_cores <- parallel::detectCores(logical = FALSE)
cl <- parallel::makeCluster(all_cores)
doParallel::registerDoParallel(cl)



svm_250_results <-
   tune_grid(
      svm250_linear_wf,
      resamples = landmarks250_folds,
      grid = svm250_grid
  )

svm250_best_accuracy <- svm_250_results %>% select_best("accuracy")

svm_250_results %>% 
  collect_metrics() %>%
  arrange(desc(mean))

final_svm250 <- svm250_linear_wf %>% 
  finalize_workflow(select_best(svm_250_results, "accuracy"))


# svm250_fit <- last_fit(final_svm250, landmarks250_split)


svm250_final_ <- 
  finalize_model(
    svm250_linear_tune,
    svm250_best_accuracy
  )

all_cores <- parallel::detectCores(logical = FALSE)
cl <- parallel::makeCluster(all_cores - 1)
doParallel::registerDoParallel(cl)


svm250_final_wf <- 
  workflow() %>%
  add_recipe(landmarks250_rec) %>%
  add_model(svm250_final_)



all_cores <- parallel::detectCores(logical = FALSE)
cl <- parallel::makeCluster(all_cores - 1)
doParallel::registerDoParallel(cl)

svm_250_final_result <-
  svm250_final_wf %>% 
  last_fit(landmarks250_split)


svm_250_final_result %>% collect_metrics()
```

```{r}
svm_250_final_result$.workflow[[1]]

svm_250_final_result$.predictions
  
svm_250_final_result$.metrics[[1]]
```

```{r}
write.csv(data.frame(svm_250_final_result$.predictions), "svm250_pred.csv", row.names = FALSE)
```


```{r}
svm250_fitobj <- pull_workflow_fit(svm250_final_wf)$fit

svm250_coef   <- svm250_fitobj@coef[[1]]

svm250_mat    <- svm250_fitobj@xmatrix[[1]]

svm250_varimp <- svm250_coef %*% svm250_mat
```

