---
title: "svm_150_samples"
author: "Mihkail Cornell"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(parallel)

doParallel::registerDoParallel()
set.seed(342)

svm150_linear_tune <-
  svm_linear(
    cost = tune()
  ) %>%
  set_mode("classification") %>%
  set_engine("kernlab")

svm150_grid <- 
  expand.grid(cost = c(0.25, 0.5, 0.75, 
                        1, 1.25, 1.5))


svm150_linear_wf <-
  workflow() %>%
  add_recipe(landmarks150_rec) %>%
  add_model(svm150_linear_tune)

# Tuning is faster in parallel
all_cores <- parallel::detectCores(logical = FALSE)
cl <- makeCluster(all_cores)
doParallel::registerDoParallel(cl)



svm_150_results <-
   tune_grid(
      svm150_linear_wf,
      resamples = landmarks150_folds,
      grid = svm150_grid
  )
```

```{r}
svm150_best_accuracy <- svm_150_results %>% select_best("accuracy")

svm_150_results %>% 
  collect_metrics() %>%
  arrange(desc(mean))

final_svm150 <- svm150_linear_wf %>% 
  finalize_workflow(select_best(svm_150_results, "accuracy"))


svm150_fitted <- last_fit(final_svm150, landmarks150_split)


svm150_final_ <- 
  finalize_model(
    svm150_linear_tune,
    svm150_best_accuracy
  )


svm150_final_wf <- 
  workflow() %>%
  add_recipe(landmarks150_rec) %>%
  add_model(svm150_final_)


svm_150_final_result <-
  svm150_final_wf %>% 
  last_fit(landmarks150_split)


svm_150_final_result %>% collect_metrics()
```

```{r}
svm_150_final_result$.workflow[[1]]

svm_150_final_result$.predictions
  
svm_150_final_result$.metrics[[1]]


write.csv(data.frame(svm_150_final_result$.predictions), "svm150_pred.csv", row.names = FALSE)
```

```{r}
extract_workflow(svm150_fitted)
```

```{r}
svm150_bake <- landmarks150_rec %>% prep() %>% bake(new_data = NULL)
```


```{r}

svm150_fitobj <- extract_workflow_set_result(svm_150_final_result, "train/test split")

svm150_coef   <- svm150_fitobj@coef[[1]]

svm150_mat    <- svm150_fitobj@xmatrix[[1]]

svm150_varimp <- svm150_coef %*% svm150_mat


extract_spec_parsnip(svm_150_final_result)
extract_fit_parsnip(svm_150_final_result)
extract_fit_engine(svm_150_final_result)


svm_150_final_result %>% 
    collect_predictions() %>%
    group_by(image_class) %>%
    roc_curve(image_class, c(.pred_admin, 
                             .pred_gate, 
                             .pred_malakas_maganda,
                             .pred_root_crops)) %>%
    ggplot(aes(1-specificity, sensitivity, color = image_class)) +
    geom_abline(lty = 2, color = "gray80", size = 1.8) +
    geom_path(show.legend = FALSE, alpha = 0.6, size = 1.2) +
    coord_equal()

```





